// <auto-generated />
namespace Store2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddDeliveryMethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDeliveryMethod));
        
        string IMigrationMetadata.Id
        {
            get { return "202406020028317_AddDeliveryMethod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
